#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
    - name: "update and upgrade apt packages"
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        # cache_valid_time: 86400 #One day
    
    - name: restart server
      shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
      async: 1
      poll: 0
      become: true
    
    - name: Wait for server to restart
      become: false
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=10
        
    - name: set timezone to Europe/London
      timezone:
        name: Europe/London
    
    - name: install pre-req packages
      apt: name={{item}} state=latest update_cache=yes
      with_items:
      - libunwind8
      - libunwind8-dev
      - gettext    
      - libicu-dev
      - liblttng-ust-dev
      - libcurl4-openssl-dev
      - uuid-dev 
      
    - name: Create dotnet directory if it does not exist
      file:
        path: /home/pi/dotnet
        state: directory
        mode: 0755    
        
    - name: Get dotnet core
      unarchive:
        src: https://github.com/dotnet/core-setup/files/716356/dotnet-ubuntu.16.04-arm.1.2.0-beta-001291-00.tar.gz
        dest: /home/pi/dotnet
        creates: /home/pi/dotnet
        remote_src: yes
        
    # export PATH=$PATH:$HOME/dotnet    
    
    - name: Create powershell directory if it does not exist
      file:
        path: /home/pi/powershell
        state: directory
        mode: 0755   
    
    - name: Get Powershell 6 core
      unarchive:
        src: https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell-6.0.1-linux-arm32.tar.gz
        dest: /home/pi/powershell
        creates: /home/pi/powershell
        remote_src: yes

    # - name: Download and extract dotnet-dev-centos-x64.1.0.0-preview2-1-003177.tar.gz
      # unarchive:
        # src: http://download.microsoft.com/download/A/F/6/AF610E6A-1D2D-47D8-80B8-F178951A0C72/Binaries/dotnet-dev-centos-x64.1.0.0-preview2-1-003177.tar.gz
        # dest: /opt/dotnet
        # copy: no
    
    # - name: Create symbolic link if it does not exist - ln -s /opt/dotnet/dotnet /usr/local/bin/dotnet
      # file:
        # src: /opt/dotnet/dotnet
        # dest: /usr/local/bin/dotnet
        # state: link
  roles:
    - role: xdrum.rsyslog
      rsyslog_server_udp_port: 514
      rsyslog_server_udp_address: 192.168.0.67
